# Generated by Django 6.0.4 on 2026-05-10 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('color', models.CharField(default='#4CAF82', max_length=20)),
                ('icon_name', models.CharField(default='grass_rounded', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('feed_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_info', to='feed.feedtype')),
            ],
        ),
        migrations.CreateModel(
            name='FeedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flock_name', models.CharField(max_length=100)),
                ('is_done', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.feedtype')),
            ],
        ),
        migrations.CreateModel(
            name='FeedPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.feedtype')),
            ],
        ),
        migrations.CreateModel(
            name='FeedNutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('protein_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('energy_kcal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calcium_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('phosphorus_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.feedtype')),
            ],
        ),
        migrations.CreateModel(
            name='FeedConsumptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flock_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.feedtype')),
            ],
        ),
    ]
